name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t angular-app .

    - name: Save Docker Image
      run: |
        docker save angular-app -o angular-app.tar

    - name: Copy Image to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "angular-app.tar"
        target: "/home/ec2-user/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop angular-container || true
          docker rm angular-container || true
          docker rmi angular-app || true
          docker load -i angular-app.tar
          docker run -d -p 80:80 --name angular-container angular-app
